FROM openjdk:17.0.2-jdk-slim as build
WORKDIR application
ENV MMS5_ROOT_CONTEXT http://layer1-service
ENV MMS5_QUERY_URL http://quad-server:3030/ds/sparql
ENV MMS5_UPDATE_URL http://quad-server:3030/ds/update
ENV MMS5_GRAPH_STORE_PROTOCOL_URL http://quad-server:3030/ds/data
COPY . .
RUN apt-get update && apt-get install -y procps
ENTRYPOINT ["/application/gradlew", "test"]