version: '3.8'

services:
  quadstore-test-server:
    image: atomgraph/fuseki:latest
    command: --mem /ds
    ports:
      - 3030:3030

  minio-server:
    image: minio/minio:latest
    environment:
      - "MINIO_ACCESS_KEY=admintest"
      - "MINIO_SECRET_KEY=admintest"
    command: server /tmp/data
    ports:
      - 9000:9000

  store-service:
    image: openmbee/mms5-store-service:latest
    environment:
      - JWT_DOMAIN=
      - JWT_AUDIENCE=
      - JWT_REALM=
      - JWT_SECRET=
    depends_on:
      - minio-server
    ports:
      - 8080:8080

  layer1-service:
    build: .
    container_name: mms
    hostname: mms
    environment:
      - JWT_DOMAIN=
      - JWT_AUDIENCE=
      - JWT_REALM=
      - JWT_SECRET=
    depends_on:
      - quadstore-test-server
      - auth-service
      - store-service
    ports:
      - 8080:8080